version: '3.8'

services:
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  php:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PHP_IDE_CONFIG="serverName=laravel-docker"
      - PHP_MEMORY_LIMIT=512M
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      php:
        condition: service_healthy

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
